### ISSUE TITLE
Multiple choice questions

### ISSUE THREAD

**Issue by willfindlay** [HousedHorse/3004-final#6]
- we need lots of multiple choice questions
- they go in questions.md
- follow the provided example

**Comment by lama97** [comment]
I did these while doing Section about testing : 

**Who does testing?**
- developers not involved in design or implementation
- specialized testers

**Verification and configuration management happens in** 
a) Fault avoidance 
b) Fault detection 
c) Fault tolerance

**Testing and debugging happens in** 
a) Fault avoidance 
b) Fault detection 
c) Fault tolerance

**Recovering from faults and failures in terms happens in :** 
a) Fault avoidance 
b) Fault detection 
c) Fault tolerance

**All of these are types of System Testings except:**
a) Functional testing
b) Usability Testing 
c) Performance Testing
d) Acceptance Testing

**One of these testings is mainly performed by the client:**
a) Functional testing
b) Usability Testing 
c) Performance Testing
d) Acceptance Testing

**_______ simulates the called portion of the code:**
a) Test drivers
b) Test stubs
c) Unit Testing

**________ testing requires no test stubs:**
a) Big bang Testing
b) Path Testing
c) Bottom-Up Testing
d) Polymorphism Testing

**________ testing requires no test drivers but MANY test stubs:**
a) Big bang Testing
b) Path Testing
c) Top-down Testing
d) Polymorphism Testing

**Which system Testing has most of its cases derived from functional requirements?**
a) Field Testing
b) Functional Testing 
c) Acceptance Testing

**System is deemed validated when :** 
a) functional and acceptance testing has no failures
b) functional and path testing has no failures
c) functional and performance testing has no failures

**Comment by lama97** [comment]
**Containers are type of :**
a) implementation inheritance
b) specification inheritance
c) delegation

**Two types of contracts associated with an operation:**
a) post condition and pre condition 
b) pre condition and invariant
c) invariant and post condition 

**Example of optimizing object model for expensive results like frequently called operations :** 
a) caching 
b) forward engineering
c) reverse engineering

**_______ is a solution for optimizing "many" side associations :**
a) contracts
b) qualified associations


**______ is a meta model for data:**
a) schema
b) primary key 
c) foreign key
